import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Title } from '../components/Title'
import styles from '../styles/Home.module.css'
import Card from '../components/Card/Card'



export default function Home() {
  const [name, setName] = useState()
  const [data, setData] = useState([])
  const nomb = ["NextJs", "PHP", "Python"];

  useEffect(() => {
    fetch('/api/getCards')
      .then(data => data.json())
      .then(jsonData => {
        setInterval(() => {
          setData(jsonData)
        }, 1000);

        setInterval(() => {
          setName(nomb[0])
        }, 1000);
        console.log(jsonData);
      })
  }, [])

  const cambiar = () => {
    setName('Juan')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Title nombre={name === '' ? "noname" : name}></Title>

        <button onClick={cambiar}>Cambiar Nombre</button>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {data.length > 0 && data.map(card => <Card key={card.key} title={card.title} description={card.description}></Card>)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
